name: build-android-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Pull Source Code 
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Setup Fastlane
        run: gem install fastlane 

      - name: Build App 
        env: 
            AC_API_TOKEN: ${{ secrets.ANDROID_AC_API_TOKEN }}
            WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          echo $AC_API_TOKEN >> secrets.txt
          echo $WEBHOOK_URL >> secrets.txt
          cat secrets.txt

        