name: build-android-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Pull Source Code 
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Setup Fastlane
        run: gem install fastlane 

      - name: Build App 
      - run: |
          flutter build appbundle
          cd ./android
          fastlane beta