name: build-android-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
      - run: flutter build appbundle
      - name: Install fastlane
        run: gem install fastlane 
      - run: |
          cd ./android
          pwd
          fastlane beta
